
security:
    encoders:
        Afsy\Entity\Author: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        entity:
            entity: { class: App:Author, property: email }

    firewalls:
        secured_area:
            pattern:        ^/
            logout:         ~
            anonymous:      ~
            oauth:
                resource_owners:
                    sensio_connect: sensio_connect_login
                login_path:     hwi_oauth_connect
                use_forward:    false
                failure_path:   hwi_oauth_connect

                oauth_user_provider:
                    service: App\OAuth\Provider\AuthorEntityProvider

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
